name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools

    - name: Build and publish package to PyPI
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        python setup.py sdist bdist_wheel
        python -m pip install --upgrade twine
        twine upload --repository pypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.UPLOAD_PASSWORD_API }}
